name: Build Examples

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  push:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: v1.18.x
          cache: true
      - name: Examples tests
        run: go run mage.go testExamples
      - name: Build examples
      - run: go run mage.go buildExamples
